apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAv+H5+Tt94cQ7ZUOnHCnWCulr+yrFx5epGscQ2I1hdR3Z0G/Ae2j2eNHEwvpdQtdAZkxZ8f2yfHeVxvbLrs6UN04yWgXxSNNxY6BXQk9y1f3oq2he1Qu0OVsQ+dQluuElcRQUQv23aZ0Z0lWAYijyGGO4Ncd4ibnSCDNx5IcssHYGN0h8YYmNhZ7LNWenA6dxl5zOVVxtd0QfEbpTEL3F7tZHbIXEWCGt+sJe+++/WzzfxswvxhoF9fz3FgTqws8denQnlPPVmFkI+4leBeAVmvQoVDKGxiTHVK4rnUEBrWBSUeQ1EXzHr1xW29JTPoSc76DXxYXdQ+/jp6lVkwCaChhwsJDOsr2mQbVxfFRl/q3g8TrYgXfh4PuxkQ//PvuUTM/Z6fBzptXs4un9peWfYAKq14hWQz0xrMKiDCEcSQ64luauqe95oqwz55ygggj5S520aLxMEZwIq5lpM3Ckpg+KOvW0UR5qJLvrC9KZj4SrmnGZhcM9ff9YiDAPhhl4sjAmtFTd63fbO2xU4yBBg7aoxSvk2pId5+ngzTog+KTPiEBZW6HH7xIxL8x5q8P+5m4n4dcp6L9JadVot2fE05Mfs9GESKDyLycw8wuoTCHZiNv35Q5yyZ0lRfrYqqmQ2M9oFv+7jqok/aEy/gQ2hiMuqdsC1WcO9Y6Tb2RclF6C9byku33/Kfj/tAOTzHZ6lpi9zOv757tRpC5xmImX88bzX0Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
